/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HelloPosiChain } from "./HelloPosiChain";
export * as factories from "./factories";
export { HelloPosiChain__factory } from "./factories/HelloPosiChain__factory";
