/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  HelloPosiChain,
  HelloPosiChainInterface,
} from "../HelloPosiChain";

const _abi = [
  {
    inputs: [],
    name: "addMoney",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "decrementCounter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getMoneyStored",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "incrementCounter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405260008055600060015534801561001957600080fd5b50610264806100296000396000f3fe60806040526004361061004a5760003560e01c80631b3f48421461004f5780635b34b96614610059578063a87d942c14610070578063e0a438fb1461009b578063f5c5ad83146100c6575b600080fd5b6100576100dd565b005b34801561006557600080fd5b5061006e6100f8565b005b34801561007c57600080fd5b50610085610113565b604051610092919061015a565b60405180910390f35b3480156100a757600080fd5b506100b061011c565b6040516100bd919061015a565b60405180910390f35b3480156100d257600080fd5b506100db610126565b005b34600160008282546100ef91906101a4565b92505081905550565b600160008082825461010a91906101a4565b92505081905550565b60008054905090565b6000600154905090565b600160008082825461013891906101fa565b92505081905550565b6000819050919050565b61015481610141565b82525050565b600060208201905061016f600083018461014b565b92915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006101af82610141565b91506101ba83610141565b9250827fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff038211156101ef576101ee610175565b5b828201905092915050565b600061020582610141565b915061021083610141565b92508282101561022357610222610175565b5b82820390509291505056fea2646970667358221220551aadde086f48dd5b06363ed6833262d5c18ee1dd764e8e3aa5db2e2b5312f664736f6c63430008090033";

type HelloPosiChainConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: HelloPosiChainConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class HelloPosiChain__factory extends ContractFactory {
  constructor(...args: HelloPosiChainConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<HelloPosiChain> {
    return super.deploy(overrides || {}) as Promise<HelloPosiChain>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): HelloPosiChain {
    return super.attach(address) as HelloPosiChain;
  }
  override connect(signer: Signer): HelloPosiChain__factory {
    return super.connect(signer) as HelloPosiChain__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): HelloPosiChainInterface {
    return new utils.Interface(_abi) as HelloPosiChainInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): HelloPosiChain {
    return new Contract(address, _abi, signerOrProvider) as HelloPosiChain;
  }
}
